/**
 * Class Gift implementation.
 * 
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  All rights reserved.
 *
 * @author Jan Minar <rdancer@rdancer.org> 
 */
public class Gift
{
    /**
     * Constructor for objects of class Gift
     */
    public Gift()
    {
        // Constructor stub generated by BlueJ    
    }

}
